### PR TITLE
Add instructions to install via scoop

### PR DESCRIPTION
**Pull request by rasa**
See https://github.com/lukesampson/scoop/blob/master/bucket/mailsend-go.json

### CODE REVIEW

**Comment by muquit** [comment]
Please update scoop json file for v1.0.5 if you have access to it.
Thanks

**Comment by rasa** [comment]
@muquit: Updated to v1.0.5 in https://github.com/ScoopInstaller/Main/commit/85d0eaddbd317be9ff9b837f94695793921963dd

**Comment by sitiom** [comment]
@muquit Why is Scoop removed from the documentation? https://github.com/muquit/mailsend-go/commit/b6a9fcd94af1fb31ef64aca6b4b4878f2ef1f35a

In any case, I have created a PR to update and fix the manifest:
- https://github.com/ScoopInstaller/Main/pull/8166

**Comment by muquit** [comment]
Thanks for updating the manifest in ScoopInstaller/Main and for the heads up!  Updated the README with instructions. If you need to update anything, please update `docs/downloading.md` (not README.md, which is generated) and send a pull request.

**Pull request merged**
